allservices = [
    {"logo": "website/images/services/air-conditioner.svg", "name": "A/C Repair", "description": "Air conditioners have become an essential component of our daily life, so timely services are also necessary.", "link": "service1", "available": True},
    {"logo": "website/images/services/water-heater.svg", "name": "Geyser Repair", "description": "Geysers must be repaired and serviced regularly for optimal usage and output because it is an electrical device.", "link": "service2", "available": True},
    {"logo": "website/images/services/washing-machine.svg", "name": "Washing Machine Repair", "description": "We offer effective and efficient servicing for all washing machine models by using their authentic spare parts.", "link": "service3", "available": True},
    {"logo": "website/images/services/refrigerator.svg", "name": "Refrigerator Repair", "description": "TRefrigerator significance intensifies during the hotter summer months, and mechanics are well trained to carry out a wide range of refrigerator repair services.", "link": "service4", "available": True},
    {"logo": "website/images/services/microwave-oven.svg", "name": "Microwave Repair", "description": "The microwave oven is unquestionably the most utilized equipment in the kitchen, and if you want any repair services, contact us immediately.", "link": "service5", "available": True},
    {"logo": "website/images/services/water-purifier.svg", "name": "Water Purifier Repair", "description": "Water purifiers are essential for every household, and we provide the best repair services for all types of water purifiers.", "link": "service7", "available": True},
    {"logo": "website/images/services/wire-coil.svg", "name": "Wire Fitting", "description": "Wire fitting is the operation done on a charged particle by an electric field, and we are here to provide you with the services.", "link": "service6", "available": False},
]

testimonials = [
    {"name": "Mohammad Aadil", "designation": "Homemaker", "message": "Sehrawat AC Works has been a lifesaver! Their technicians are professional, prompt, and highly skilled. My AC was up and running in no time, and I couldn’t be happier with the service. Highly recommended! They are our go-to for all repair needs."},
    {"name": "Mohammad Aadil Sehrawat", "designation": "Business Owner", "message": "Sehrawat AC Works provided exceptional service for our office building. The technicians were knowledgeable, courteous, and efficient. Our AC units are now running perfectly, and the entire process was seamless. We will definitely use their services again!"},
    {"name": "Aadil Sehrawat", "designation": "Property Manager", "message": "I've worked with many service providers, but Sehrawat AC Works stands out for their reliability and expertise. Their team consistently delivers top-notch service, ensuring our properties remain comfortable for all tenants."},
]